include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    prefer_const_constructors: true
    public_member_api_docs: false
    comment_references: false
    slash_for_doc_comments: false